# Generated by Django 3.0.2 on 2020-01-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('phone', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('aadhar', models.CharField(max_length=20)),
                ('phelped', models.IntegerField()),
                ('last_loc', models.CharField(max_length=200)),
                ('avg_rating', models.FloatField()),
            ],
        ),
    ]
