# Generated by Django 3.0.2 on 2020-01-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpnet', '0002_auto_20200111_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avg_rating',
            field=models.CharField(blank=True, default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phelped',
            field=models.CharField(blank=True, default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='verified',
            field=models.CharField(default=False, max_length=6),
        ),
    ]
