# Generated by Django 3.0.2 on 2020-01-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpnet', '0005_auto_20200113_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_made',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uid', to='helpnet.person'),
        ),
    ]
