# Generated by Django 3.0.2 on 2020-01-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpnet', '0007_auto_20200114_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='req_made',
            name='passigned_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='req_made',
            name='presponded_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
