# Generated by Django 3.0.2 on 2020-01-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpnet', '0008_auto_20200114_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req_made',
            name='req_time',
            field=models.CharField(max_length=200),
        ),
    ]
