# Generated by Django 3.0.2 on 2020-01-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpnet', '0009_auto_20200115_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='loc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('last_loc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='req_made',
            name='auth_resp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='req_made',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='req_made',
            name='nprespond',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
