# Generated by Django 3.0.2 on 2020-01-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpnet', '0010_auto_20200117_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loc',
            name='last_loc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
